spring:
  jpa:
    show_sql: true   # System out
    ddl-auto: create
    properties:
      hibernate:
        dialect=org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  profiles:
    include: oauth

  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
